### ISSUE TITLE
Whois Spice - Additional Updates Needed

### ISSUE THREAD

**Issue by abeyang** [duckduckgo/zeroclickinfo-spice#1414]
We need to make updates to https://github.com/duckduckgo/zeroclickinfo-spice/pull/1331. In the end, it should look like this:

![screen shot 2015-01-14 at 2 14 36 pm](https://cloud.githubusercontent.com/assets/794084/5748809/b3474672-9bf7-11e4-8126-f268fc77bd6c.png)

Changes:
- Remove byline completely ("whois lookup")
- CSS changes:

``` css
.zci--whois .zci__more-at { padding-top: 0; }
.zci--whois .record td { padding-left: 0; }
.zci--whois .record .record__cell__key { text-transform: capitalize; }
```

Finally, we need to make these changes (not shown):
- Remove colons at the end of each key
- "Expires" should be "Expires On"

And that's it!
